<?php

namespace Inc\Base;

class Activate
{
    public static function activate(){
        global $wpdb, $table_prefix;
    $wp_donation = $table_prefix . 'donation';

    $q = "CREATE TABLE IF NOT EXISTS `$wp_donation` (
        `id` INT(50) NOT NULL AUTO_INCREMENT , 
      `full_name` VARCHAR(100) NOT NULL , 
      `email` VARCHAR(100) NOT NULL , 
      `contact` TEXT NOT NULL , 
      `PAN` TEXT NOT NULL , 
      `amount` TEXT NOT NULL , 
      `status` BOOLEAN NOT NULL , 
      `date` DATE NOT NULL , 
      PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;";
    $wpdb->query($q);

    // Insert dummy data if needed
    
    $data = array(
        'full_name' => 'Akshay',
        'email' => 'akshay@gmai.com',
        'contact' => '9349413345',
        'PAN' => 'FGEOP2398K',
        'amount' => '100',
        'status' => 0,
        'Date' => current_time('mysql')
    );

    $wpdb->insert($wp_donation,$data);

    //contact form 
    $wp_spiral_contact_form = $table_prefix . 'spiral_contact_form';

    $table2 = "CREATE TABLE IF NOT EXISTS `$wp_spiral_contact_form` (
        `id` INT(50) NOT NULL AUTO_INCREMENT ,  
        `name` TEXT NOT NULL , 
        `email` TEXT NOT NULL , 
        `contact` TEXT NOT NULL , 
        `subject` TEXT NOT NULL , 
        `message` TEXT NOT NULL , 
        `date` DATE NOT NULL , 
        PRIMARY KEY (`id`)) 
        ENGINE = InnoDB;";

    $wpdb->query($table2);

     // Insert dummy data if needed
    
     $contact_form_data = array(
        'name' => 'Bear',
        'email' => 'bear@gmail.com',
        'contact' => '9349413345',
        'subject' => 'Hello world',
        'message' => 'This is working',
        'date' => current_time('mysql')
    );

    $wpdb->insert($wp_spiral_contact_form,$contact_form_data);


    //volunteer form
    $wp_spiral_volunteer_form = $table_prefix . 'spiral_volunteer_form';

    $table3 = "CREATE TABLE IF NOT EXISTS `$wp_spiral_volunteer_form` (
        `id` INT(50) NOT NULL AUTO_INCREMENT ,  
        `name` TEXT NOT NULL , 
        `email` TEXT NOT NULL , 
        `aadhaar` TEXT NOT NULL , 
        `age` TEXT NOT NULL , 
        `profession` TEXT NOT NULL , 
        `duration` TEXT NOT NULL , 
        `preferences` TEXT NOT NULL , 
        `availability` TEXT NOT NULL , 
        `contact` TEXT NOT NULL , 
        `address_1` TEXT NOT NULL , 
        `address_2` TEXT NOT NULL , 
        `city` TEXT NOT NULL , 
        `state` TEXT NOT NULL , 
        `zip` TEXT NOT NULL , 
        `country` TEXT NOT NULL , 
        `comments` TEXT NOT NULL , 
        `date` DATE NOT NULL , 
        PRIMARY KEY (`id`)) 
        ENGINE = InnoDB;";

    $wpdb->query($table3);

     // Insert dummy data if needed
    
     $volunteer_form_data = array(
        'name' => 'Goku',
        'email' => 'goku@gmail.com',
        'aadhaar' => '9349413345',
        'age' => '18 years - 25 years',
        'profession' => 'student',
        'duration' => '1',
        'preferences' => 'POSH',
        'availability' => 'Weekdays',
        'contact' => '8989877767',
        'address_1' => 'India',
        'address_2' => 'USA',
        'city' => 'Hyderabad',
        'state' => 'Jharkhand',
        'zip' => '500032',
        'country' => 'India',
        'comments' => 'This is working',
        'date' => current_time('mysql')
    );

    $wpdb->insert($wp_spiral_volunteer_form,$volunteer_form_data);

    //states
    $wp_states = $table_prefix . 'states';

    $table4 = "CREATE TABLE IF NOT EXISTS `$wp_states` (
        `id` INT(50) NOT NULL AUTO_INCREMENT ,  
        `states` TEXT NOT NULL , 
        `mid` TEXT NOT NULL , 
        PRIMARY KEY (`id`)) 
        ENGINE = InnoDB;";

    $wpdb->query($table4);

     // Insert state data
    
     $states_data = array(
        array('states' => 'Andhra Pradesh', 'mid' => '1'),
        array('states' => 'Arunachal Pradesh', 'mid' => '2'),
        array('states' => 'Assam', 'mid' => '3'),
        array('states' => 'Bihar', 'mid' => '4'),
        array('states' => 'Chhattisgarh', 'mid' => '5'),
        array('states' => 'Goa', 'mid' => '6'),
        array('states' => 'Gujarat', 'mid' => '7'),
        array('states' => 'Haryana', 'mid' => '8'),
        array('states' => 'Himachal Pradesh', 'mid' => '9'),
        array('states' => 'Jharkhand', 'mid' => '10'),
        array('states' => 'Karnataka', 'mid' => '11'),
        array('states' => 'Kerala', 'mid' => '12'),
        array('states' => 'Madhya Pradesh', 'mid' => '13'),
        array('states' => 'Maharashtra', 'mid' => '14'),
        array('states' => 'Manipur', 'mid' => '15'),
        array('states' => 'Meghalaya', 'mid' => '16'),
        array('states' => 'Mizoram', 'mid' => '17'),
        array('states' => 'Nagaland', 'mid' => '18'),
        array('states' => 'Odisha', 'mid' => '19'),
        array('states' => 'Punjab', 'mid' => '20'),
        array('states' => 'Rajasthan', 'mid' => '21'),
        array('states' => 'Sikkim', 'mid' => '22'),
        array('states' => 'Tamil Nadu', 'mid' => '23'),
        array('states' => 'Telangana', 'mid' => '24'),
        array('states' => 'Tripura', 'mid' => '25'),
        array('states' => 'Uttar Pradesh', 'mid' => '26'),
        array('states' => 'Uttarakhand', 'mid' => '27'),
        array('states' => 'West Bengal', 'mid' => '28'),
        // Union Territories
        array('states' => 'Andaman and Nicobar Islands', 'mid' => '29'),
        array('states' => 'Chandigarh', 'mid' => '30'),
        array('states' => 'Dadra and Nagar Haveli and Daman and Diu', 'mid' => '31'),
        array('states' => 'Lakshadweep', 'mid' => '32'),
        array('states' => 'Delhi (National Capital Territory of Delhi)', 'mid' => '33'),
        array('states' => 'Puducherry (Pondicherry)', 'mid' => '34'),
        array('states' => 'Ladakh', 'mid' => '35'),
    );
    

    foreach ($states_data as $data) {
        $wpdb->insert($wp_states, $data);
    }

    //districts
    $wp_districts = $table_prefix . 'districts';

    $table5 = "CREATE TABLE IF NOT EXISTS `$wp_districts` (
        `id` INT(50) NOT NULL AUTO_INCREMENT ,  
        `districts` TEXT NOT NULL , 
        `mid` TEXT NOT NULL , 
        PRIMARY KEY (`id`)) 
        ENGINE = InnoDB;";

    $wpdb->query($table5);

    $district_data = array(
        array('districts' => 'Anantapur', 'mid' => '1'),
        array('districts' => 'Chittoor', 'mid' => '1'),
        array('districts' => 'East Godavari', 'mid' => '1'),
        array('districts' => 'Guntur', 'mid' => '1'),
        array('districts' => 'Krishna', 'mid' => '1'),
        array('districts' => 'Kurnool', 'mid' => '1'),
        array('districts' => 'Prakasam', 'mid' => '1'),
        array('districts' => 'Sri Potti Sriramulu Nellore', 'mid' => '1'),
        array('districts' => 'Srikakulam', 'mid' => '1'),
        array('districts' => 'Visakhapatnam', 'mid' => '1'),
        array('districts' => 'Vizianagaram', 'mid' => '1'),
        array('districts' => 'West Godavari', 'mid' => '1'),
        array('districts' => 'YSR Kadapa (Y.S.R. district)', 'mid' => '1'),
        array('districts' => 'Tawang', 'mid' => '2'),
        array('districts' => 'West Kameng', 'mid' => '2'),
        array('districts' => 'East Kameng', 'mid' => '2'),
        array('districts' => 'Papum Pare', 'mid' => '2'),
        array('districts' => 'Kurung Kumey', 'mid' => '2'),
        array('districts' => 'Kra Daadi', 'mid' => '2'),
        array('districts' => 'Lower Subansiri', 'mid' => '2'),
        array('districts' => 'Upper Subansiri', 'mid' => '2'),
        array('districts' => 'West Siang', 'mid' => '2'),
        array('districts' => 'East Siang', 'mid' => '2'),
        array('districts' => 'Siang', 'mid' => '2'),
        array('districts' => 'Upper Siang', 'mid' => '2'),
        array('districts' => 'Lower Siang', 'mid' => '2'),
        array('districts' => 'Lower Dibang Valley', 'mid' => '2'),
        array('districts' => 'Upper Dibang Valley', 'mid' => '2'),
        array('districts' => 'Anjaw', 'mid' => '2'),
        array('districts' => 'Lohit', 'mid' => '2'),
        array('districts' => 'Namsai', 'mid' => '2'),
        array('districts' => 'Changlang', 'mid' => '2'),
        array('districts' => 'Tirap', 'mid' => '2'),
        array('districts' => 'Longding', 'mid' => '2'),
        array('districts' => 'Baksa', 'mid' => '3'),
        array('districts' => 'Barpeta', 'mid' => '3'),
        array('districts' => 'Biswanath', 'mid' => '3'),
        array('districts' => 'Bongaigaon', 'mid' => '3'),
        array('districts' => 'Cachar', 'mid' => '3'),
        array('districts' => 'Charaideo', 'mid' => '3'),
        array('districts' => 'Chirang', 'mid' => '3'),
        array('districts' => 'Darrang', 'mid' => '3'),
        array('districts' => 'Dhemaji', 'mid' => '3'),
        array('districts' => 'Dhubri', 'mid' => '3'),
        array('districts' => 'Dibrugarh', 'mid' => '3'),
        array('districts' => 'Dima Hasao', 'mid' => '3'),
        array('districts' => 'Goalpara', 'mid' => '3'),
        array('districts' => 'Golaghat', 'mid' => '3'),
        array('districts' => 'Hailakandi', 'mid' => '3'),
        array('districts' => 'Hojai', 'mid' => '3'),
        array('districts' => 'Jorhat', 'mid' => '3'),
        array('districts' => 'Kamrup', 'mid' => '3'),
        array('districts' => 'Kamrup Metropolitan', 'mid' => '3'),
        array('districts' => 'Karbi Anglong', 'mid' => '3'),
        array('districts' => 'Karimganj', 'mid' => '3'),
        array('districts' => 'Kokrajhar', 'mid' => '3'),
        array('districts' => 'Lakhimpur', 'mid' => '3'),
        array('districts' => 'Majuli', 'mid' => '3'),
        array('districts' => 'Morigaon', 'mid' => '3'),
        array('districts' => 'Nagaon', 'mid' => '3'),
        array('districts' => 'Nalbari', 'mid' => '3'),
        array('districts' => 'Sivasagar', 'mid' => '3'),
        array('districts' => 'Sonitpur', 'mid' => '3'),
        array('districts' => 'South Salmara-Mankachar', 'mid' => '3'),
        array('districts' => 'Tinsukia', 'mid' => '3'),
        array('districts' => 'Udalguri', 'mid' => '3'),
        array('districts' => 'West Karbi Anglong', 'mid' => '3'),
        array('districts' => 'Araria', 'mid' => '4'),
        array('districts' => 'Arwal', 'mid' => '4'),
        array('districts' => 'Aurangabad', 'mid' => '4'),
        array('districts' => 'Banka', 'mid' => '4'),
        array('districts' => 'Begusarai', 'mid' => '4'),
        array('districts' => 'Bhagalpur', 'mid' => '4'),
        array('districts' => 'Bhojpur', 'mid' => '4'),
        array('districts' => 'Buxar', 'mid' => '4'),
        array('districts' => 'Darbhanga', 'mid' => '4'),
        array('districts' => 'East Champaran', 'mid' => '4'),
        array('districts' => 'Gaya', 'mid' => '4'),
        array('districts' => 'Gopalganj', 'mid' => '4'),
        array('districts' => 'Jamui', 'mid' => '4'),
        array('districts' => 'Jehanabad', 'mid' => '4'),
        array('districts' => 'Kaimur', 'mid' => '4'),
        array('districts' => 'Katihar', 'mid' => '4'),
        array('districts' => 'Khagaria', 'mid' => '4'),
        array('districts' => 'Kishanganj', 'mid' => '4'),
        array('districts' => 'Lakhisarai', 'mid' => '4'),
        array('districts' => 'Madhepura', 'mid' => '4'),
        array('districts' => 'Madhubani', 'mid' => '4'),
        array('districts' => 'Munger', 'mid' => '4'),
        array('districts' => 'Muzaffarpur', 'mid' => '4'),
        array('districts' => 'Nalanda', 'mid' => '4'),
        array('districts' => 'Nawada', 'mid' => '4'),
        array('districts' => 'Patna', 'mid' => '4'),
        array('districts' => 'Purnia', 'mid' => '4'),
        array('districts' => 'Rohtas', 'mid' => '4'),
        array('districts' => 'Saharsa', 'mid' => '4'),
        array('districts' => 'Samastipur', 'mid' => '4'),
        array('districts' => 'Saran', 'mid' => '4'),
        array('districts' => 'Sheikhpura', 'mid' => '4'),
        array('districts' => 'Sheohar', 'mid' => '4'),
        array('districts' => 'Sitamarhi', 'mid' => '4'),
        array('districts' => 'Siwan', 'mid' => '4'),
        array('districts' => 'Supaul', 'mid' => '4'),
        array('districts' => 'Vaishali', 'mid' => '4'),
        array('districts' => 'West Champaran', 'mid' => '4'),
        array('districts' => 'Balod', 'mid' => '5'),
        array('districts' => 'Baloda Bazar', 'mid' => '5'),
        array('districts' => 'Balrampur', 'mid' => '5'),
        array('districts' => 'Bastar', 'mid' => '5'),
        array('districts' => 'Bemetara', 'mid' => '5'),
        array('districts' => 'Bijapur', 'mid' => '5'),
        array('districts' => 'Bilaspur', 'mid' => '5'),
        array('districts' => 'Dantewada', 'mid' => '5'),
        array('districts' => 'Dhamtari', 'mid' => '5'),
        array('districts' => 'Durg', 'mid' => '5'),
        array('districts' => 'Gariaband', 'mid' => '5'),
        array('districts' => 'Janjgir-Champa', 'mid' => '5'),
        array('districts' => 'Jashpur', 'mid' => '5'),
        array('districts' => 'Kanker', 'mid' => '5'),
        array('districts' => 'Kondagaon', 'mid' => '5'),
        array('districts' => 'Korba', 'mid' => '5'),
        array('districts' => 'Koriya', 'mid' => '5'),
        array('districts' => 'Mahasamund', 'mid' => '5'),
        array('districts' => 'Mungeli', 'mid' => '5'),
        array('districts' => 'Narayanpur', 'mid' => '5'),
        array('districts' => 'Raigarh', 'mid' => '5'),
        array('districts' => 'Raipur', 'mid' => '5'),
        array('districts' => 'Rajnandgaon', 'mid' => '5'),
        array('districts' => 'Sukma', 'mid' => '5'),
        array('districts' => 'Surajpur', 'mid' => '5'),
        array('districts' => 'Surguja', 'mid' => '5'),
        array('districts' => 'North Goa', 'mid' => '6'),
        array('districts' => 'South Goa', 'mid' => '6'),
        array('districts' => 'Ahmedabad', 'mid' => '7'),
        array('districts' => 'Amreli', 'mid' => '7'),
        array('districts' => 'Anand', 'mid' => '7'),
        array('districts' => 'Aravalli', 'mid' => '7'),
        array('districts' => 'Banaskantha', 'mid' => '7'),
        array('districts' => 'Bharuch', 'mid' => '7'),
        array('districts' => 'Bhavnagar', 'mid' => '7'),
        array('districts' => 'Botad', 'mid' => '7'),
        array('districts' => 'Chhota Udaipur', 'mid' => '7'),
        array('districts' => 'Dahod', 'mid' => '7'),
        array('districts' => 'Dang', 'mid' => '7'),
        array('districts' => 'Devbhoomi Dwarka', 'mid' => '7'),
        array('districts' => 'Gandhinagar', 'mid' => '7'),
        array('districts' => 'Gir Somnath', 'mid' => '7'),
        array('districts' => 'Jamnagar', 'mid' => '7'),
        array('districts' => 'Junagadh', 'mid' => '7'),
        array('districts' => 'Kheda', 'mid' => '7'),
        array('districts' => 'Kutch', 'mid' => '7'),
        array('districts' => 'Mahisagar', 'mid' => '7'),
        array('districts' => 'Mehsana', 'mid' => '7'),
        array('districts' => 'Morbi', 'mid' => '7'),
        array('districts' => 'Narmada', 'mid' => '7'),
        array('districts' => 'Navsari', 'mid' => '7'),
        array('districts' => 'Panchmahal', 'mid' => '7'),
        array('districts' => 'Patan', 'mid' => '7'),
        array('districts' => 'Porbandar', 'mid' => '7'),
        array('districts' => 'Rajkot', 'mid' => '7'),
        array('districts' => 'Sabarkantha', 'mid' => '7'),
        array('districts' => 'Surat', 'mid' => '7'),
        array('districts' => 'Surendranagar', 'mid' => '7'),
        array('districts' => 'Tapi', 'mid' => '7'),
        array('districts' => 'Vadodara', 'mid' => '7'),
        array('districts' => 'Valsad', 'mid' => '7'),
        array('districts' => 'Ambala', 'mid' => '8'),
        array('districts' => 'Bhiwani', 'mid' => '8'),
        array('districts' => 'Charkhi Dadri', 'mid' => '8'),
        array('districts' => 'Faridabad', 'mid' => '8'),
        array('districts' => 'Fatehabad', 'mid' => '8'),
        array('districts' => 'Gurugram', 'mid' => '8'),
        array('districts' => 'Hisar', 'mid' => '8'),
        array('districts' => 'Jhajjar', 'mid' => '8'),
        array('districts' => 'Jind', 'mid' => '8'),
        array('districts' => 'Kaithal', 'mid' => '8'),
        array('districts' => 'Karnal', 'mid' => '8'),
        array('districts' => 'Kurukshetra', 'mid' => '8'),
        array('districts' => 'Mahendragarh', 'mid' => '8'),
        array('districts' => 'Nuh', 'mid' => '8'),
        array('districts' => 'Palwal', 'mid' => '8'),
        array('districts' => 'Panchkula', 'mid' => '8'),
        array('districts' => 'Panipat', 'mid' => '8'),
        array('districts' => 'Rewari', 'mid' => '8'),
        array('districts' => 'Rohtak', 'mid' => '8'),
        array('districts' => 'Sirsa', 'mid' => '8'),
        array('districts' => 'Sonipat', 'mid' => '8'),
        array('districts' => 'Yamunanagar', 'mid' => '8'),
        array('districts' => 'Bilaspur', 'mid' => '9'),
        array('districts' => 'Chamba', 'mid' => '9'),
        array('districts' => 'Hamirpur', 'mid' => '9'),
        array('districts' => 'Kangra', 'mid' => '9'),
        array('districts' => 'Kinnaur', 'mid' => '9'),
        array('districts' => 'Kullu', 'mid' => '9'),
        array('districts' => 'Lahaul and Spiti', 'mid' => '9'),
        array('districts' => 'Mandi', 'mid' => '9'),
        array('districts' => 'Shimla', 'mid' => '9'),
        array('districts' => 'Sirmaur', 'mid' => '9'),
        array('districts' => 'Solan', 'mid' => '9'),
        array('districts' => 'Una', 'mid' => '9'),
        array('districts' => 'Bokaro', 'mid' => '10'),
        array('districts' => 'Chatra', 'mid' => '10'),
        array('districts' => 'Deoghar', 'mid' => '10'),
        array('districts' => 'Dhanbad', 'mid' => '10'),
        array('districts' => 'Dumka', 'mid' => '10'),
        array('districts' => 'East Singhbhum', 'mid' => '10'),
        array('districts' => 'Garhwa', 'mid' => '10'),
        array('districts' => 'Giridih', 'mid' => '10'),
        array('districts' => 'Godda', 'mid' => '10'),
        array('districts' => 'Gumla', 'mid' => '10'),
        array('districts' => 'Hazaribagh', 'mid' => '10'),
        array('districts' => 'Jamtara', 'mid' => '10'),
        array('districts' => 'Khunti', 'mid' => '10'),
        array('districts' => 'Koderma', 'mid' => '10'),
        array('districts' => 'Latehar', 'mid' => '10'),
        array('districts' => 'Lohardaga', 'mid' => '10'),
        array('districts' => 'Pakur', 'mid' => '10'),
        array('districts' => 'Palamu', 'mid' => '10'),
        array('districts' => 'Ramgarh', 'mid' => '10'),
        array('districts' => 'Ranchi', 'mid' => '10'),
        array('districts' => 'Sahebganj', 'mid' => '10'),
        array('districts' => 'Seraikela Kharsawan', 'mid' => '10'),
        array('districts' => 'Simdega', 'mid' => '10'),
        array('districts' => 'West Singhbhum', 'mid' => '10'),
        array('districts' => 'Bagalkot', 'mid' => '11'),
        array('districts' => 'Ballari (Bellary)', 'mid' => '11'),
        array('districts' => 'Belagavi (Belgaum)', 'mid' => '11'),
        array('districts' => 'Bengaluru Rural', 'mid' => '11'),
        array('districts' => 'Bengaluru Urban', 'mid' => '11'),
        array('districts' => 'Bidar', 'mid' => '11'),
        array('districts' => 'Chamarajanagar', 'mid' => '11'),
        array('districts' => 'Chikkaballapur', 'mid' => '11'),
        array('districts' => 'Chikkamagaluru (Chikmagalur)', 'mid' => '11'),
        array('districts' => 'Chitradurga', 'mid' => '11'),
        array('districts' => 'Dakshina Kannada', 'mid' => '11'),
        array('districts' => 'Davanagere', 'mid' => '11'),
        array('districts' => 'Dharwad', 'mid' => '11'),
        array('districts' => 'Gadag', 'mid' => '11'),
        array('districts' => 'Hassan', 'mid' => '11'),
        array('districts' => 'Haveri', 'mid' => '11'),
        array('districts' => 'Kalaburagi (Gulbarga)', 'mid' => '11'),
        array('districts' => 'Kodagu', 'mid' => '11'),
        array('districts' => 'Kolar', 'mid' => '11'),
        array('districts' => 'Koppal', 'mid' => '11'),
        array('districts' => 'Mandya', 'mid' => '11'),
        array('districts' => 'Mysuru (Mysore)', 'mid' => '11'),
        array('districts' => 'Raichur', 'mid' => '11'),
        array('districts' => 'Ramanagara', 'mid' => '11'),
        array('districts' => 'Shivamogga (Shimoga)', 'mid' => '11'),
        array('districts' => 'Tumakuru (Tumkur)', 'mid' => '11'),
        array('districts' => 'Udupi', 'mid' => '11'),
        array('districts' => 'Uttara Kannada (Karwar)', 'mid' => '11'),
        array('districts' => 'Vijayapura (Bijapur)', 'mid' => '11'),
        array('districts' => 'Yadgir', 'mid' => '11'),
        array('districts' => 'Alappuzha', 'mid' => '12'),
        array('districts' => 'Ernakulam', 'mid' => '12'),
        array('districts' => 'Idukki', 'mid' => '12'),
        array('districts' => 'Kannur', 'mid' => '12'),
        array('districts' => 'Kasaragod', 'mid' => '12'),
        array('districts' => 'Kollam', 'mid' => '12'),
        array('districts' => 'Kottayam', 'mid' => '12'),
        array('districts' => 'Kozhikode', 'mid' => '12'),
        array('districts' => 'Malappuram', 'mid' => '12'),
        array('districts' => 'Palakkad', 'mid' => '12'),
        array('districts' => 'Pathanamthitta', 'mid' => '12'),
        array('districts' => 'Thiruvananthapuram', 'mid' => '12'),
        array('districts' => 'Thrissur', 'mid' => '12'),
        array('districts' => 'Wayanad', 'mid' => '12'),
        array('districts' => 'Agar Malwa', 'mid' => '13'),
        array('districts' => 'Alirajpur', 'mid' => '13'),
        array('districts' => 'Anuppur', 'mid' => '13'),
        array('districts' => 'Ashoknagar', 'mid' => '13'),
        array('districts' => 'Balaghat', 'mid' => '13'),
        array('districts' => 'Barwani', 'mid' => '13'),
        array('districts' => 'Betul', 'mid' => '13'),
        array('districts' => 'Bhind', 'mid' => '13'),
        array('districts' => 'Bhopal', 'mid' => '13'),
        array('districts' => 'Burhanpur', 'mid' => '13'),
        array('districts' => 'Chhatarpur', 'mid' => '13'),
        array('districts' => 'Chhindwara', 'mid' => '13'),
        array('districts' => 'Damoh', 'mid' => '13'),
        array('districts' => 'Datia', 'mid' => '13'),
        array('districts' => 'Dewas', 'mid' => '13'),
        array('districts' => 'Dhar', 'mid' => '13'),
        array('districts' => 'Dindori', 'mid' => '13'),
        array('districts' => 'Guna', 'mid' => '13'),
        array('districts' => 'Gwalior', 'mid' => '13'),
        array('districts' => 'Harda', 'mid' => '13'),
        array('districts' => 'Hoshangabad', 'mid' => '13'),
        array('districts' => 'Indore', 'mid' => '13'),
        array('districts' => 'Jabalpur', 'mid' => '13'),
        array('districts' => 'Jhabua', 'mid' => '13'),
        array('districts' => 'Katni', 'mid' => '13'),
        array('districts' => 'Khandwa', 'mid' => '13'),
        array('districts' => 'Khargone', 'mid' => '13'),
        array('districts' => 'Mandla', 'mid' => '13'),
        array('districts' => 'Mandsaur', 'mid' => '13'),
        array('districts' => 'Morena', 'mid' => '13'),
        array('districts' => 'Narsinghpur', 'mid' => '13'),
        array('districts' => 'Neemuch', 'mid' => '13'),
        array('districts' => 'Panna', 'mid' => '13'),
        array('districts' => 'Raisen', 'mid' => '13'),
        array('districts' => 'Rajgarh', 'mid' => '13'),
        array('districts' => 'Ratlam', 'mid' => '13'),
        array('districts' => 'Rewa', 'mid' => '13'),
        array('districts' => 'Sagar', 'mid' => '13'),
        array('districts' => 'Satna', 'mid' => '13'),
        array('districts' => 'Sehore', 'mid' => '13'),
        array('districts' => 'Seoni', 'mid' => '13'),
        array('districts' => 'Shahdol', 'mid' => '13'),
        array('districts' => 'Shajapur', 'mid' => '13'),
        array('districts' => 'Sheopur', 'mid' => '13'),
        array('districts' => 'Shivpuri', 'mid' => '13'),
        array('districts' => 'Sidhi', 'mid' => '13'),
        array('districts' => 'Singrauli', 'mid' => '13'),
        array('districts' => 'Tikamgarh', 'mid' => '13'),
        array('districts' => 'Ujjain', 'mid' => '13'),
        array('districts' => 'Umaria', 'mid' => '13'),
        array('districts' => 'Vidisha', 'mid' => '13'),
        array('districts' => 'Ahmednagar', 'mid' => '14'),
        array('districts' => 'Akola', 'mid' => '14'),
        array('districts' => 'Amravati', 'mid' => '14'),
        array('districts' => 'Aurangabad', 'mid' => '14'),
        array('districts' => 'Beed', 'mid' => '14'),
        array('districts' => 'Bhandara', 'mid' => '14'),
        array('districts' => 'Buldhana', 'mid' => '14'),
        array('districts' => 'Chandrapur', 'mid' => '14'),
        array('districts' => 'Dhule', 'mid' => '14'),
        array('districts' => 'Gadchiroli', 'mid' => '14'),
        array('districts' => 'Gondia', 'mid' => '14'),
        array('districts' => 'Hingoli', 'mid' => '14'),
        array('districts' => 'Jalgaon', 'mid' => '14'),
        array('districts' => 'Jalna', 'mid' => '14'),
        array('districts' => 'Kolhapur', 'mid' => '14'),
        array('districts' => 'Latur', 'mid' => '14'),
        array('districts' => 'Mumbai City', 'mid' => '14'),
        array('districts' => 'Mumbai Suburban', 'mid' => '14'),
        array('districts' => 'Nagpur', 'mid' => '14'),
        array('districts' => 'Nanded', 'mid' => '14'),
        array('districts' => 'Nandurbar', 'mid' => '14'),
        array('districts' => 'Nashik', 'mid' => '14'),
        array('districts' => 'Osmanabad', 'mid' => '14'),
        array('districts' => 'Palghar', 'mid' => '14'),
        array('districts' => 'Parbhani', 'mid' => '14'),
        array('districts' => 'Pune', 'mid' => '14'),
        array('districts' => 'Raigad', 'mid' => '14'),
        array('districts' => 'Ratnagiri', 'mid' => '14'),
        array('districts' => 'Sangli', 'mid' => '14'),
        array('districts' => 'Satara', 'mid' => '14'),
        array('districts' => 'Sindhudurg', 'mid' => '14'),
        array('districts' => 'Solapur', 'mid' => '14'),
        array('districts' => 'Thane', 'mid' => '14'),
        array('districts' => 'Wardha', 'mid' => '14'),
        array('districts' => 'Washim', 'mid' => '14'),
        array('districts' => 'Yavatmal', 'mid' => '14'),
        array('districts' => 'Bishnupur', 'mid' => '15'),
        array('districts' => 'Chandel', 'mid' => '15'),
        array('districts' => 'Churachandpur', 'mid' => '15'),
        array('districts' => 'Imphal East', 'mid' => '15'),
        array('districts' => 'Imphal West', 'mid' => '15'),
        array('districts' => 'Jiribam', 'mid' => '15'),
        array('districts' => 'Kakching', 'mid' => '15'),
        array('districts' => 'Kamjong', 'mid' => '15'),
        array('districts' => 'Kangpokpi', 'mid' => '15'),
        array('districts' => 'Noney', 'mid' => '15'),
        array('districts' => 'Pherzawl', 'mid' => '15'),
        array('districts' => 'Senapati', 'mid' => '15'),
        array('districts' => 'Tamenglong', 'mid' => '15'),
        array('districts' => 'Tengnoupal', 'mid' => '15'),
        array('districts' => 'Thoubal', 'mid' => '15'),
        array('districts' => 'Ukhrul', 'mid' => '15'),
        array('districts' => 'East Garo Hills', 'mid' => '16'),
        array('districts' => 'East Jaintia Hills', 'mid' => '16'),
        array('districts' => 'East Khasi Hills', 'mid' => '16'),
        array('districts' => 'North Garo Hills', 'mid' => '16'),
        array('districts' => 'Ribhoi', 'mid' => '16'),
        array('districts' => 'South Garo Hills', 'mid' => '16'),
        array('districts' => 'South West Garo Hills', 'mid' => '16'),
        array('districts' => 'South West Khasi Hills', 'mid' => '16'),
        array('districts' => 'West Garo Hills', 'mid' => '16'),
        array('districts' => 'West Jaintia Hills', 'mid' => '16'),
        array('districts' => 'West Khasi Hills', 'mid' => '16'),
        array('districts' => 'Aizawl', 'mid' => '17'),
        array('districts' => 'Champhai', 'mid' => '17'),
        array('districts' => 'Hnahthial', 'mid' => '17'),
        array('districts' => 'Khawzawl', 'mid' => '17'),
        array('districts' => 'Kolasib', 'mid' => '17'),
        array('districts' => 'Lawngtlai', 'mid' => '17'),
        array('districts' => 'Lunglei', 'mid' => '17'),
        array('districts' => 'Mamit', 'mid' => '17'),
        array('districts' => 'Saiha', 'mid' => '17'),
        array('districts' => 'Serchhip', 'mid' => '17'),
        array('districts' => 'Dimapur', 'mid' => '18'),
        array('districts' => 'Kiphire', 'mid' => '18'),
        array('districts' => 'Kohima', 'mid' => '18'),
        array('districts' => 'Longleng', 'mid' => '18'),
        array('districts' => 'Mokokchung', 'mid' => '18'),
        array('districts' => 'Mon', 'mid' => '18'),
        array('districts' => 'Peren', 'mid' => '18'),
        array('districts' => 'Phek', 'mid' => '18'),
        array('districts' => 'Tuensang', 'mid' => '18'),
        array('districts' => 'Wokha', 'mid' => '18'),
        array('districts' => 'Zunheboto', 'mid' => '18'),
        array('districts' => 'Angul', 'mid' => '19'),
        array('districts' => 'Balangir', 'mid' => '19'),
        array('districts' => 'Balasore (Baleswar)', 'mid' => '19'),
        array('districts' => 'Bargarh (Baragarh)', 'mid' => '19'),
        array('districts' => 'Bhadrak', 'mid' => '19'),
        array('districts' => 'Boudh (Bauda)', 'mid' => '19'),
        array('districts' => 'Cuttack', 'mid' => '19'),
        array('districts' => 'Deogarh (Debagarh)', 'mid' => '19'),
        array('districts' => 'Dhenkanal', 'mid' => '19'),
        array('districts' => 'Gajapati', 'mid' => '19'),
        array('districts' => 'Ganjam', 'mid' => '19'),
        array('districts' => 'Jagatsinghpur', 'mid' => '19'),
        array('districts' => 'Jajpur', 'mid' => '19'),
        array('districts' => 'Jharsuguda', 'mid' => '19'),
        array('districts' => 'Kalahandi', 'mid' => '19'),
        array('districts' => 'Kandhamal', 'mid' => '19'),
        array('districts' => 'Kendrapara', 'mid' => '19'),
        array('districts' => 'Kendujhar (Keonjhar)', 'mid' => '19'),
        array('districts' => 'Khordha', 'mid' => '19'),
        array('districts' => 'Koraput', 'mid' => '19'),
        array('districts' => 'Malkangiri', 'mid' => '19'),
        array('districts' => 'Mayurbhanj', 'mid' => '19'),
        array('districts' => 'Nabarangpur', 'mid' => '19'),
        array('districts' => 'Nayagarh', 'mid' => '19'),
        array('districts' => 'Nuapada', 'mid' => '19'),
        array('districts' => 'Puri', 'mid' => '19'),
        array('districts' => 'Rayagada', 'mid' => '19'),
        array('districts' => 'Sambalpur', 'mid' => '19'),
        array('districts' => 'Subarnapur (Sonepur)', 'mid' => '19'),
        array('districts' => 'Sundargarh', 'mid' => '19'),
        array('districts' => 'Amritsar', 'mid' => '20'),
        array('districts' => 'Barnala', 'mid' => '20'),
        array('districts' => 'Bathinda', 'mid' => '20'),
        array('districts' => 'Faridkot', 'mid' => '20'),
        array('districts' => 'Fatehgarh Sahib', 'mid' => '20'),
        array('districts' => 'Fazilka', 'mid' => '20'),
        array('districts' => 'Ferozepur', 'mid' => '20'),
        array('districts' => 'Gurdaspur', 'mid' => '20'),
        array('districts' => 'Hoshiarpur', 'mid' => '20'),
        array('districts' => 'Jalandhar', 'mid' => '20'),
        array('districts' => 'Kapurthala', 'mid' => '20'),
        array('districts' => 'Ludhiana', 'mid' => '20'),
        array('districts' => 'Mansa', 'mid' => '20'),
        array('districts' => 'Moga', 'mid' => '20'),
        array('districts' => 'Muktsar', 'mid' => '20'),
        array('districts' => 'Pathankot', 'mid' => '20'),
        array('districts' => 'Patiala', 'mid' => '20'),
        array('districts' => 'Rupnagar', 'mid' => '20'),
        array('districts' => 'Sahibzada Ajit Singh Nagar (Mohali)', 'mid' => '20'),
        array('districts' => 'Sangrur', 'mid' => '20'),
        array('districts' => 'Shahid Bhagat Singh Nagar (Nawanshahr)', 'mid' => '20'),
        array('districts' => 'Sri Muktsar Sahib', 'mid' => '20'),
        array('districts' => 'Tarn Taran', 'mid' => '20'),
        array('districts' => 'Ajmer', 'mid' => '21'),
        array('districts' => 'Alwar', 'mid' => '21'),
        array('districts' => 'Banswara', 'mid' => '21'),
        array('districts' => 'Baran', 'mid' => '21'),
        array('districts' => 'Barmer', 'mid' => '21'),
        array('districts' => 'Bharatpur', 'mid' => '21'),
        array('districts' => 'Bhilwara', 'mid' => '21'),
        array('districts' => 'Bikaner', 'mid' => '21'),
        array('districts' => 'Bundi', 'mid' => '21'),
        array('districts' => 'Chittorgarh', 'mid' => '21'),
        array('districts' => 'Churu', 'mid' => '21'),
        array('districts' => 'Dausa', 'mid' => '21'),
        array('districts' => 'Dholpur', 'mid' => '21'),
        array('districts' => 'Dungarpur', 'mid' => '21'),
        array('districts' => 'Hanumangarh', 'mid' => '21'),
        array('districts' => 'Jaipur', 'mid' => '21'),
        array('districts' => 'Jaisalmer', 'mid' => '21'),
        array('districts' => 'Jalore', 'mid' => '21'),
        array('districts' => 'Jhalawar', 'mid' => '21'),
        array('districts' => 'Jhunjhunu', 'mid' => '21'),
        array('districts' => 'Jodhpur', 'mid' => '21'),
        array('districts' => 'Karauli', 'mid' => '21'),
        array('districts' => 'Kota', 'mid' => '21'),
        array('districts' => 'Nagaur', 'mid' => '21'),
        array('districts' => 'Pali', 'mid' => '21'),
        array('districts' => 'Pratapgarh', 'mid' => '21'),
        array('districts' => 'Rajsamand', 'mid' => '21'),
        array('districts' => 'Sawai Madhopur', 'mid' => '21'),
        array('districts' => 'Sikar', 'mid' => '21'),
        array('districts' => 'Sirohi', 'mid' => '21'),
        array('districts' => 'Sri Ganganagar', 'mid' => '21'),
        array('districts' => 'Tonk', 'mid' => '21'),
        array('districts' => 'Udaipur', 'mid' => '21'),
        array('districts' => 'East Sikkim', 'mid' => '22'),
        array('districts' => 'North Sikkim', 'mid' => '22'),
        array('districts' => 'South Sikkim', 'mid' => '22'),
        array('districts' => 'West Sikkim', 'mid' => '22'),
        array('districts' => 'Ariyalur', 'mid' => '23'),
    array('districts' => 'Chengalpattu', 'mid' => '23'),
    array('districts' => 'Chennai', 'mid' => '23'),
    array('districts' => 'Coimbatore', 'mid' => '23'),
    array('districts' => 'Cuddalore', 'mid' => '23'),
    array('districts' => 'Dharmapuri', 'mid' => '23'),
    array('districts' => 'Dindigul', 'mid' => '23'),
    array('districts' => 'Erode', 'mid' => '23'),
    array('districts' => 'Kallakurichi', 'mid' => '23'),
    array('districts' => 'Kanchipuram', 'mid' => '23'),
    array('districts' => 'Kanyakumari', 'mid' => '23'),
    array('districts' => 'Karur', 'mid' => '23'),
    array('districts' => 'Krishnagiri', 'mid' => '23'),
    array('districts' => 'Madurai', 'mid' => '23'),
    array('districts' => 'Mayiladuthurai', 'mid' => '23'),
    array('districts' => 'Nagapattinam', 'mid' => '23'),
    array('districts' => 'Namakkal', 'mid' => '23'),
    array('districts' => 'Nilgiris', 'mid' => '23'),
    array('districts' => 'Perambalur', 'mid' => '23'),
    array('districts' => 'Pudukkottai', 'mid' => '23'),
    array('districts' => 'Ramanathapuram', 'mid' => '23'),
    array('districts' => 'Ranipet', 'mid' => '23'),
    array('districts' => 'Salem', 'mid' => '23'),
    array('districts' => 'Sivaganga', 'mid' => '23'),
    array('districts' => 'Tenkasi', 'mid' => '23'),
    array('districts' => 'Thanjavur', 'mid' => '23'),
    array('districts' => 'Theni', 'mid' => '23'),
    array('districts' => 'Thoothukudi (Tuticorin)', 'mid' => '23'),
    array('districts' => 'Tiruchirappalli', 'mid' => '23'),
    array('districts' => 'Tirunelveli', 'mid' => '23'),
    array('districts' => 'Tirupathur', 'mid' => '23'),
    array('districts' => 'Tiruppur', 'mid' => '23'),
    array('districts' => 'Tiruvallur', 'mid' => '23'),
    array('districts' => 'Tiruvannamalai', 'mid' => '23'),
    array('districts' => 'Tiruvarur', 'mid' => '23'),
    array('districts' => 'Vellore', 'mid' => '23'),
    array('districts' => 'Viluppuram', 'mid' => '23'),
    array('districts' => 'Virudhunagar', 'mid' => '23'),
    array('districts' => 'Adilabad', 'mid' => '24'),
    array('districts' => 'Bhadradri Kothagudem', 'mid' => '24'),
    array('districts' => 'Hyderabad', 'mid' => '24'),
    array('districts' => 'Jagtial', 'mid' => '24'),
    array('districts' => 'Jangaon', 'mid' => '24'),
    array('districts' => 'Jayashankar Bhupalpally', 'mid' => '24'),
    array('districts' => 'Jogulamba Gadwal', 'mid' => '24'),
    array('districts' => 'Kamareddy', 'mid' => '24'),
    array('districts' => 'Karimnagar', 'mid' => '24'),
    array('districts' => 'Khammam', 'mid' => '24'),
    array('districts' => 'Komaram Bheem Asifabad', 'mid' => '24'),
    array('districts' => 'Mahabubabad', 'mid' => '24'),
    array('districts' => 'Mahabubnagar', 'mid' => '24'),
    array('districts' => 'Mancherial', 'mid' => '24'),
    array('districts' => 'Medak', 'mid' => '24'),
    array('districts' => 'Medchal–Malkajgiri', 'mid' => '24'),
    array('districts' => 'Mulugu', 'mid' => '24'),
    array('districts' => 'Nagarkurnool', 'mid' => '24'),
    array('districts' => 'Nalgonda', 'mid' => '24'),
    array('districts' => 'Narayanpet', 'mid' => '24'),
    array('districts' => 'Nirmal', 'mid' => '24'),
    array('districts' => 'Nizamabad', 'mid' => '24'),
    array('districts' => 'Peddapalli', 'mid' => '24'),
    array('districts' => 'Rajanna Sircilla', 'mid' => '24'),
    array('districts' => 'Rangareddy', 'mid' => '24'),
    array('districts' => 'Sangareddy', 'mid' => '24'),
    array('districts' => 'Siddipet', 'mid' => '24'),
    array('districts' => 'Suryapet', 'mid' => '24'),
    array('districts' => 'Vikarabad', 'mid' => '24'),
    array('districts' => 'Wanaparthy', 'mid' => '24'),
    array('districts' => 'Warangal Rural', 'mid' => '24'),
    array('districts' => 'Warangal Urban', 'mid' => '24'),
    array('districts' => 'Yadadri Bhuvanagiri', 'mid' => '24'),  
    array('districts' => 'Dhalai', 'mid' => '25'),
    array('districts' => 'Gomati', 'mid' => '25'),
    array('districts' => 'Khowai', 'mid' => '25'),
    array('districts' => 'North Tripura', 'mid' => '25'),
    array('districts' => 'Sepahijala', 'mid' => '25'),
    array('districts' => 'South Tripura', 'mid' => '25'),
    array('districts' => 'Unakoti', 'mid' => '25'),
    array('districts' => 'West Tripura', 'mid' => '25'),
    array('districts' => 'Agra', 'mid' => '26'),
    array('districts' => 'Aligarh', 'mid' => '26'),
    array('districts' => 'Allahabad', 'mid' => '26'),
    array('districts' => 'Ambedkar Nagar', 'mid' => '26'),
    array('districts' => 'Amethi', 'mid' => '26'),
    array('districts' => 'Amroha', 'mid' => '26'),
    array('districts' => 'Auraiya', 'mid' => '26'),
    array('districts' => 'Azamgarh', 'mid' => '26'),
    array('districts' => 'Baghpat', 'mid' => '26'),
    array('districts' => 'Bahraich', 'mid' => '26'),
    array('districts' => 'Ballia', 'mid' => '26'),
    array('districts' => 'Balrampur', 'mid' => '26'),
    array('districts' => 'Banda', 'mid' => '26'),
    array('districts' => 'Barabanki', 'mid' => '26'),
    array('districts' => 'Bareilly', 'mid' => '26'),
    array('districts' => 'Basti', 'mid' => '26'),
    array('districts' => 'Bijnor', 'mid' => '26'),
    array('districts' => 'Budaun', 'mid' => '26'),
    array('districts' => 'Bulandshahr', 'mid' => '26'),
    array('districts' => 'Chandauli', 'mid' => '26'),
    array('districts' => 'Chitrakoot', 'mid' => '26'),
    array('districts' => 'Deoria', 'mid' => '26'),
    array('districts' => 'Etah', 'mid' => '26'),
    array('districts' => 'Etawah', 'mid' => '26'),
    array('districts' => 'Faizabad', 'mid' => '26'),
    array('districts' => 'Farrukhabad', 'mid' => '26'),
    array('districts' => 'Fatehpur', 'mid' => '26'),
    array('districts' => 'Firozabad', 'mid' => '26'),
    array('districts' => 'Gautam Buddh Nagar', 'mid' => '26'),
    array('districts' => 'Ghaziabad', 'mid' => '26'),
    array('districts' => 'Ghazipur', 'mid' => '26'),
    array('districts' => 'Gonda', 'mid' => '26'),
    array('districts' => 'Gorakhpur', 'mid' => '26'),
    array('districts' => 'Hamirpur', 'mid' => '26'),
    array('districts' => 'Hapur (Panchsheel Nagar)', 'mid' => '26'),
    array('districts' => 'Hardoi', 'mid' => '26'),
    array('districts' => 'Hathras', 'mid' => '26'),
    array('districts' => 'Jalaun', 'mid' => '26'),
    array('districts' => 'Jaunpur', 'mid' => '26'),
    array('districts' => 'Jhansi', 'mid' => '26'),
    array('districts' => 'Kannauj', 'mid' => '26'),
    array('districts' => 'Kanpur Dehat (Ramabai Nagar)', 'mid' => '26'),
    array('districts' => 'Kanpur Nagar', 'mid' => '26'),
    array('districts' => 'Kasganj', 'mid' => '26'),
    array('districts' => 'Kaushambi', 'mid' => '26'),
    array('districts' => 'Kushinagar (Padrauna)', 'mid' => '26'),
    array('districts' => 'Lakhimpur Kheri', 'mid' => '26'),
    array('districts' => 'Lalitpur', 'mid' => '26'),
    array('districts' => 'Lucknow', 'mid' => '26'),
    array('districts' => 'Maharajganj', 'mid' => '26'),
    array('districts' => 'Mahoba', 'mid' => '26'),
    array('districts' => 'Mainpuri', 'mid' => '26'),
    array('districts' => 'Mathura', 'mid' => '26'),
    array('districts' => 'Mau', 'mid' => '26'),
    array('districts' => 'Meerut', 'mid' => '26'),
    array('districts' => 'Mirzapur', 'mid' => '26'),
    array('districts' => 'Moradabad', 'mid' => '26'),
    array('districts' => 'Muzaffarnagar', 'mid' => '26'),
    array('districts' => 'Pilibhit', 'mid' => '26'),
    array('districts' => 'Pratapgarh', 'mid' => '26'),
    array('districts' => 'Prayagraj (Allahabad)', 'mid' => '26'),
    array('districts' => 'Raebareli', 'mid' => '26'),
    array('districts' => 'Rampur', 'mid' => '26'),
    array('districts' => 'Saharanpur', 'mid' => '26'),
    array('districts' => 'Sambhal', 'mid' => '26'),
    array('districts' => 'Sant Kabir Nagar', 'mid' => '26'),
    array('districts' => 'Shahjahanpur', 'mid' => '26'),
    array('districts' => 'Shamli', 'mid' => '26'),
    array('districts' => 'Shrawasti', 'mid' => '26'),
    array('districts' => 'Siddharthnagar', 'mid' => '26'),
    array('districts' => 'Sitapur', 'mid' => '26'),
    array('districts' => 'Sonbhadra', 'mid' => '26'),
    array('districts' => 'Sultanpur', 'mid' => '26'),
    array('districts' => 'Unnao', 'mid' => '26'),
    array('districts' => 'Varanasi', 'mid' => '26'),
    array('districts' => 'Almora', 'mid' => '27'),
    array('districts' => 'Bageshwar', 'mid' => '27'),
    array('districts' => 'Chamoli', 'mid' => '27'),
    array('districts' => 'Champawat', 'mid' => '27'),
    array('districts' => 'Dehradun', 'mid' => '27'),
    array('districts' => 'Haridwar', 'mid' => '27'),
    array('districts' => 'Nainital', 'mid' => '27'),
    array('districts' => 'Pauri Garhwal', 'mid' => '27'),
    array('districts' => 'Pithoragarh', 'mid' => '27'),
    array('districts' => 'Rudraprayag', 'mid' => '27'),
    array('districts' => 'Tehri Garhwal', 'mid' => '27'),
    array('districts' => 'Udham Singh Nagar', 'mid' => '27'),
    array('districts' => 'Uttarkashi', 'mid' => '27'),
    array('districts' => 'Alipurduar', 'mid' => '28'),
    array('districts' => 'Bankura', 'mid' => '28'),
    array('districts' => 'Birbhum', 'mid' => '28'),
    array('districts' => 'Cooch Behar', 'mid' => '28'),
    array('districts' => 'Dakshin Dinajpur (South Dinajpur)', 'mid' => '28'),
    array('districts' => 'Darjeeling', 'mid' => '28'),
    array('districts' => 'Hooghly', 'mid' => '28'),
    array('districts' => 'Howrah', 'mid' => '28'),
    array('districts' => 'Jalpaiguri', 'mid' => '28'),
    array('districts' => 'Jhargram', 'mid' => '28'),
    array('districts' => 'Kalimpong', 'mid' => '28'),
    array('districts' => 'Kolkata', 'mid' => '28'),
    array('districts' => 'Malda', 'mid' => '28'),
    array('districts' => 'Murshidabad', 'mid' => '28'),
    array('districts' => 'Nadia', 'mid' => '28'),
    array('districts' => 'North 24 Parganas', 'mid' => '28'),
    array('districts' => 'Paschim Medinipur (West Medinipur)', 'mid' => '28'),
    array('districts' => 'Purba Medinipur (East Medinipur)', 'mid' => '28'),
    array('districts' => 'Purulia', 'mid' => '28'),
    array('districts' => 'South 24 Parganas', 'mid' => '28'),
    array('districts' => 'Uttar Dinajpur (North Dinajpur)', 'mid' => '28'),
    array('districts' => 'Nicobar', 'mid' => '29'),
    array('districts' => 'North and Middle Andaman', 'mid' => '29'),
    array('districts' => 'South Andaman', 'mid' => '29'),
    array('districts' => 'Chandigarh', 'mid' => '30'),
    array('districts' => 'Dadra and Nagar Haveli and Daman and Diu', 'mid' => '31'),
    array('districts' => 'Lakshadweep', 'mid' => '32'),
    array('districts' => 'Delhi (National Capital Territory of Delhi)', 'mid' => '33'),
    array('districts' => 'Puducherry (Pondicherry)', 'mid' => '34'),
    array('districts' => 'Ladakh', 'mid' => '35'),
    );


    foreach ($district_data as $data) {
        $wpdb->insert($wp_districts, $data);
    }
    

    }
}
